### ISSUE TITLE
-flto -g fails

### ISSUE THREAD

**Issue by Trass3r** [FreddieChopin/bleeding-edge-toolchain#15]
I tested the toolchain, thanks for it!
It even saves 2-3KB compared to my older 8.2 toolchain.
LTO works too but not when adding debug info (worked with the older toolchain). Can you reproduce this?
`arm-none-eabi/bin/ld.exe: error: could not unlink output file`

**Comment by Trass3r** [comment]
Ok seems to go away when removing `-save-temps`.

**Comment by Trass3r** [comment]
Reduced it, could you try if it also happens for you, maybe also on Linux:
```cpp
void yield() {}
```
```cpp
void yield();
int main() { yield(); }
```
```sh
arm-none-eabi-g++ -o obj/main.cpp.o -c -flto -g -nostdlib -O2  main.cpp
arm-none-eabi-g++ -o obj/yield.cpp.o -c -flto -g -nostdlib -O2  yield.cpp
arm-none-eabi-gcc-ar rc obj/libFrameworkArduino.a obj/main.cpp.o obj/yield.cpp.o
arm-none-eabi-g++ -o obj/firmware.elf -T empty.ld -Wl,--gc-sections -O2 -save-temps obj/libFrameworkArduino.a
```

**Comment by Trass3r** [comment]
Looks like it is a legit bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90369

**Comment by FreddieChopin** [comment]
You sorted that out even before I could try it (; After the gcc team publishes a new snapshot (10.x.x snapshot or 9.x.x snapshot if the bug report will have info about fixing this in gcc-9-branch too) you can build the new toolchain using the script - just replace `gccVersion="9.1.0"` with `gccVersion="10-YYYYMMDD"` (depending on the snapshot name) and run it again.

**Comment by Trass3r** [comment]
Yeah I guess they won't backport it to v9. `-save-temps` is not used that often. I also just use it to see the produced assembly in the case of LTO.

**Comment by FreddieChopin** [comment]
> Yeah I guess they won't backport it to v9.

You never know (; Maybe they will, try to nag them a bit if you care about that. But if you can also try the 10.x.x snapshot, then it doesn't matter that much.

> -save-temps is not used that often. I also just use it to see the produced assembly in the case of LTO.

You can inspect assembler in a different way. I just dump the assembly straight from the produced executable like this:
https://github.com/DISTORTEC/distortos/blob/master/cmake/distortos-utilities.cmake#L90
`$ arm-none-eabi-objdump --demangle -S output.elf > output.lss`

If you compile with debugging symbols, then the assembly usually is nicely mixed with the sourcecode (it gets worse with higher optimization levels).

**Comment by Trass3r** [comment]
Yeah I know but gcc's output is way better than objdump's iirc. Would need to re-check.
