### ISSUE TITLE
newlib semihosting

### ISSUE THREAD

**Issue by intractabilis** [FreddieChopin/bleeding-edge-toolchain#31]
Thank you for publishing this script. It was a great help in writing my script to build an ARM toolchain.

I have a question. I am trying to use my own toolchain as a replacement for a toolchain supplied by NXP inside their MCUXpresso. It has `libcr_newlib_semihost.a`, `libcr_newlib_nohost.a`, and `libcr_newlib_none.a`. These are not being built by your script. Do you have a clue how to build them?

**Comment by FreddieChopin** [comment]
Hello!

Your best option is either looking for something like a source-package of their toolchain or asking them directly for the sources/way-to-build, which is required by GPL license of the software. Usually they have a package with sources (for example meant for Linux/Mac) which also includes build scripts, and this way you may analyze what is what. This script is based on a source package with build scripts which was published by ARM along with their toolchain, so I suppose something like this should be also available for NXP, however it may be hidden or not so easily downloadable.

Regards,
FCh

**Comment by intractabilis** [comment]
Great. Thank you!
